package beap.commands;

import beap.Config;
import beap.Console;
import beap.Lang;
import beap.utils.PlatformUtils;
import sys.FileSystem;
import sys.io.File;
import beap.commands.Command.BaseCommand;

class SetupCommand extends BaseCommand {
    public override function execute(args:Array<String>) {
        Console.println(Lang.get("setting_up"), ConsoleColor.BOLD);
        Console.println("");
        
        if (PlatformUtils.isWindows()) {
            setupWindows();
        } else if (PlatformUtils.isMac() || PlatformUtils.isLinux()) {
            setupUnix();
        } else {
            Console.error("Unsupported OS: " + PlatformUtils.getSystemName());
            Console.println("Please manually add beap to your PATH");
        }
    }
    
    function setupWindows() {
        var beapHome = getBeapHome();
        if (beapHome == "") {
            Console.error("Cannot find beap installation directory!");
            Console.println("");
            Console.println("Make sure beap is installed via haxelib:", ConsoleColor.YELLOW);
            Console.println("  haxelib install beap", ConsoleColor.CYAN);
            printManualInstructions();
            return;
        }
        
        var haxeDir = getHaxeDir();
        if (haxeDir == "") {
            Console.error("Haxe directory not found!");
            printManualInstructions();
            return;
        }
        
        var beapCmd = haxeDir + "\\beap.cmd";
        var nekoPath = getNekoPath();
        
        var beapHomeFixed = StringTools.replace(beapHome, "/", "\\");
        
        var beapNPath = "";
        if (FileSystem.exists(beapHomeFixed + "\\run.n")) {
            beapNPath = beapHomeFixed + "\\run.n";
        } else if (FileSystem.exists(beapHomeFixed + "\\bin\\run.n")) {
            beapNPath = beapHomeFixed + "\\bin\\run.n";
        } else {
            Console.error("Cannot find run.n in: " + beapHomeFixed);
            return;
        }
        
        var content = '@echo off
    rem beap - Heaps Build Tool
    rem Generated by beap setup

    ' + nekoPath + ' "' + beapNPath + '" %*
    ';
        
        try {
            File.saveContent(beapCmd, content);
            Console.success("Created: " + beapCmd);
            Console.println("");
            Console.info("You can now use 'beap' command directly!");
            Console.println("Make sure " + haxeDir + " is in your PATH");
            Console.println("");
            Console.println("Test with: beap help", ConsoleColor.CYAN);
        } catch (e:Dynamic) {
            Console.error("Failed to create beap.cmd: " + e);
            printManualInstructions();
        }
    }
    
    function setupUnix() {
        var beapHome = getBeapHome();
        if (beapHome == "") {
            Console.error("Cannot find beap installation directory!");
            printManualInstructions();
            return;
        }
        
        var home = Sys.getEnv("HOME");
        if (home == null || home == "") {
            Console.error("HOME environment variable not found");
            printManualInstructions();
            return;
        }
        
        var localBin = home + "/.local/bin";
        if (!FileSystem.exists(localBin)) {
            try {
                FileSystem.createDirectory(localBin);
                Console.info("Created: " + localBin);
            } catch (e:Dynamic) {
                Console.warning("Could not create " + localBin);
            }
        }
        
        var beapScript = localBin + "/beap";
        var nekoPath = getNekoPath();
        
        var content = '#!/bin/bash
# beap - Heaps Build Tool
# Generated by beap setup

BEAP_HOME="' + beapHome + '"
' + nekoPath + ' "$$BEAP_HOME/bin/run.n" "$$@"
';
        
        try {
            File.saveContent(beapScript, content);
            Sys.command('chmod +x "' + beapScript + '"');
            Console.success("Created: " + beapScript);
            Console.println("");
            Console.info("You can now use 'beap' command directly!");
            Console.println("Make sure " + localBin + " is in your PATH");
            Console.println("");
            Console.println("If not, add this to your ~/.bashrc or ~/.zshrc:");
            Console.println('  export PATH="$$HOME/.local/bin:$$PATH"', ConsoleColor.CYAN);
            Console.println("");
            Console.println("Test with: beap help", ConsoleColor.CYAN);
        } catch (e:Dynamic) {
            Console.error("Failed to create beap script: " + e);
            printManualInstructions();
        }
    }
    
    function getBeapHome():String {
        try {
            var process = new sys.io.Process("haxelib", ["path", "beap"]);
            var output = process.stdout.readAll().toString();
            process.close();
            
            var lines = output.split("\n");
            if (lines.length > 0) {
                var path = StringTools.trim(lines[0]);
                while (StringTools.endsWith(path, "/") || StringTools.endsWith(path, "\\")) {
                    path = path.substr(0, path.length - 1);
                }

                var testPaths = [
                    path,
                    path + "\\bin",
                    path + "\\git",
                    StringTools.replace(path, "/git", ""),
                    StringTools.replace(path, "\\git", "")
                ];
                
                for (testPath in testPaths) {
                    if (FileSystem.exists(testPath + "\\run.n")) {
                        Console.info("Found run.n at: " + testPath);
                        return testPath;
                    }
                    if (FileSystem.exists(testPath + "\\bin\\run.n")) {
                        Console.info("Found run.n at: " + testPath + "\\bin");
                        return testPath;
                    }
                }
                
                Console.info("Using beap path: " + path);
                return path;
            }
        } catch (e:Dynamic) {
            Console.info("haxelib path beap failed: " + e);
        }
        
        // 方法2: 从当前项目的 .haxelib 目录获取
        var currentDir = Sys.getCwd();
        var haxelibLocalPath = currentDir + "\\.haxelib\\beap";
        if (FileSystem.exists(haxelibLocalPath + "\\run.n")) {
            Console.info("Found beap at local project: " + haxelibLocalPath);
            return haxelibLocalPath;
        }
        
        // 方法3: 从用户 haxelib 目录获取
        var userProfile = Sys.getEnv("USERPROFILE");
        if (userProfile != null) {
            var userHaxelibPath = userProfile + "\\haxelib\\beap";
            if (FileSystem.exists(userHaxelibPath + "\\run.n")) {
                Console.info("Found beap at user haxelib: " + userHaxelibPath);
                return userHaxelibPath;
            }
            // 也检查 git 子目录
            var userHaxelibGitPath = userProfile + "\\haxelib\\beap\\git";
            if (FileSystem.exists(userHaxelibGitPath + "\\run.n")) {
                Console.info("Found beap at user haxelib: " + userHaxelibGitPath);
                return userHaxelibGitPath;
            }
        }
        
        // 方法4: 从全局 haxelib 目录获取
        var globalPaths = [
            "C:\\HaxeToolkit\\lib\\beap",
            "C:\\HaxeToolkit\\haxe\\lib\\beap",
            "C:\\Program Files\\Haxe\\lib\\beap"
        ];
        
        for (p in globalPaths) {
            if (FileSystem.exists(p + "\\run.n")) {
                Console.info("Found beap at: " + p);
                return p;
            }
            if (FileSystem.exists(p + "\\git\\run.n")) {
                Console.info("Found beap at: " + p + "\\git");
                return p + "\\git";
            }
        }
        
        return "";
    }
    
    function getHaxeDir():String {
        // 使用 where 命令查找 haxe.exe
        try {
            var process = new sys.io.Process("where", ["haxe"]);
            var output = process.stdout.readAll().toString();
            process.close();
            var lines = output.split("\n");
            if (lines.length > 0 && lines[0] != "") {
                var haxePath = StringTools.trim(lines[0]);
                // 获取 haxe.exe 所在目录
                var lastSlash = haxePath.lastIndexOf("\\");
                if (lastSlash != -1) {
                    return haxePath.substr(0, lastSlash);
                }
            }
        } catch (e:Dynamic) {}
        
        // 常见安装路径
        var commonPaths = [
            "C:\\HaxeToolkit\\haxe",
            "C:\\Program Files\\Haxe",
            "C:\\haxe"
        ];
        
        for (p in commonPaths) {
            if (FileSystem.exists(p + "\\haxe.exe")) {
                return p;
            }
        }
        
        return "";
    }
    
    function getNekoPath():String {
        var nekoCmd = "neko";
        
        // 检查 neko 是否在 PATH 中
        var result = Sys.command(nekoCmd + " -version 2> nul");
        if (result == 0) {
            return nekoCmd;
        }
        
        // 尝试常见路径
        var commonPaths = [
            "C:\\HaxeToolkit\\neko",
            "C:\\Program Files\\Neko",
        ];
        
        for (p in commonPaths) {
            var nekoExe = p + "\\neko.exe";
            if (FileSystem.exists(nekoExe)) {
                return nekoExe;
            }
        }
        
        return "neko";
    }
    
    function printManualInstructions() {
        Console.println("");
        Console.println("Manual installation instructions:", ConsoleColor.YELLOW);
        Console.println("");
        
        Console.println("1. Run this command to find beap path:", ConsoleColor.WHITE);
        Console.println("   haxelib path beap", ConsoleColor.CYAN);
        Console.println("");
        Console.println("2. Create a file called 'beap.cmd' in your Haxe directory", ConsoleColor.WHITE);
        Console.println("3. Add this content (replace PATH with the actual path):", ConsoleColor.WHITE);
        Console.println("   @echo off", ConsoleColor.CYAN);
        Console.println("   set BEAP_HOME=PATH_FROM_ABOVE", ConsoleColor.CYAN);
        Console.println("   neko \"%BEAP_HOME%/bin/run.n\" %*", ConsoleColor.CYAN);
        Console.println("");
        Console.println("4. Make sure the Haxe directory is in your PATH", ConsoleColor.WHITE);
    }
}