package beap.commands;

import beap.Config;
import beap.Console;
import beap.Lang;
import beap.utils.PlatformUtils;
import sys.FileSystem;
import sys.io.File;
import beap.commands.Command.BaseCommand;

class SetupCommand extends BaseCommand {
    public override function execute(args:Array<String>) {
        Console.println("Setting up beap for direct access...", ConsoleColor.BOLD);
        Console.println("");
        
        if (PlatformUtils.isWindows()) {
            setupWindows();
        } else if (PlatformUtils.isMac() || PlatformUtils.isLinux()) {
            setupUnix();
        } else {
            Console.error("Unsupported OS: " + PlatformUtils.getSystemName());
            Console.println("Please manually add beap to your PATH");
        }
    }
    
    function setupWindows() {
        var haxeDir = getHaxeDir();
        if (haxeDir == "") {
            Console.error("Haxe directory not found!");
            printManualInstructions();
            return;
        }
        
        var beapCmd = haxeDir + "\\beap.cmd";
        var currentDir = StringTools.replace(Sys.getCwd(), "\\", "/");
        var nekoPath = getNekoPath();
        
        // 修复：使用字符串拼接而不是插值，避免 $ 符号被解析
        var content = '@echo off\n';
        content += 'rem beap - Heaps Build Tool\n';
        content += 'rem Generated by beap setup\n';
        content += '\n';
        content += 'set BEAP_HOME=' + currentDir + '\n';
        content += nekoPath + ' "' + currentDir + '/bin/beap.n" %*\n';
        
        try {
            File.saveContent(beapCmd, content);
            Console.success("Created: " + beapCmd);
            Console.println("");
            Console.info("You can now use 'beap' command directly!");
            Console.println("Make sure " + haxeDir + " is in your PATH");
            Console.println("");
            Console.println("Test with: beap help", ConsoleColor.CYAN);
        } catch (e:Dynamic) {
            Console.error("Failed to create beap.cmd: " + e);
            printManualInstructions();
        }
    }
    
    function setupUnix() {
        var home = Sys.getEnv("HOME");
        if (home == null || home == "") {
            Console.error("HOME environment variable not found");
            printManualInstructions();
            return;
        }
        
        var localBin = home + "/.local/bin";
        if (!FileSystem.exists(localBin)) {
            try {
                FileSystem.createDirectory(localBin);
                Console.info("Created: " + localBin);
            } catch (e:Dynamic) {
                Console.warning("Could not create " + localBin);
            }
        }
        
        var beapScript = localBin + "/beap";
        var currentDir = Sys.getCwd();
        var nekoPath = getNekoPath();
        
        // 修复：使用字符串拼接，避免 $$ 符号被解析
        // 在 bash 脚本中需要使用 $HOME 和 $BEAP_HOME，所以要用 $$ 转义
        var content = '#!/bin/bash\n';
        content += '# beap - Heaps Build Tool\n';
        content += '# Generated by beap setup\n';
        content += '\n';
        content += 'BEAP_HOME="' + currentDir + '"\n';
        content += nekoPath + ' "$$BEAP_HOME/bin/beap.n" "$$@"\n';
        
        try {
            File.saveContent(beapScript, content);
            
            // 设置执行权限
            Sys.command('chmod +x "' + beapScript + '"');
            
            Console.success("Created: " + beapScript);
            Console.println("");
            Console.info("You can now use 'beap' command directly!");
            Console.println("Make sure " + localBin + " is in your PATH");
            Console.println("");
            Console.println("If not, add this to your ~/.bashrc or ~/.zshrc:");
            Console.println('  export PATH="$$HOME/.local/bin:$$PATH"', ConsoleColor.CYAN);
            Console.println("");
            Console.println("Test with: beap help", ConsoleColor.CYAN);
        } catch (e:Dynamic) {
            Console.error("Failed to create beap script: " + e);
            printManualInstructions();
        }
    }
    
    function getHaxeDir():String {
        var path = Sys.getEnv("PATH");
        if (path == null) return "";
        
        var paths = path.split(";");
        
        for (p in paths) {
            if (FileSystem.exists(p + "\\haxe.exe")) {
                return p;
            }
        }
        
        var commonPaths = [
            "C:\\HaxeToolkit\\haxe",
            "C:\\Program Files\\Haxe",
            "C:\\haxe"
        ];
        
        for (p in commonPaths) {
            if (FileSystem.exists(p + "\\haxe.exe")) {
                return p;
            }
        }
        
        return "";
    }
    
    function getNekoPath():String {
        var nekoCmd = "neko";
        
        // 检查 neko 是否在 PATH 中
        #if windows
        var result = Sys.command(nekoCmd + " -version 2> nul");
        #else
        var result = Sys.command(nekoCmd + " -version 2>/dev/null");
        #end
        
        if (result == 0) {
            return nekoCmd;
        }
        
        if (PlatformUtils.isWindows()) {
            var commonPaths = [
                "C:\\HaxeToolkit\\neko",
                "C:\\Program Files\\Neko",
            ];
            
            for (p in commonPaths) {
                var nekoExe = p + "\\neko.exe";
                if (FileSystem.exists(nekoExe)) {
                    return nekoExe;
                }
            }
        } else {
            var commonPaths = [
                "/usr/bin/neko",
                "/usr/local/bin/neko"
            ];
            
            for (p in commonPaths) {
                if (FileSystem.exists(p)) {
                    return p;
                }
            }
        }
        
        return "neko";
    }
    
    function printManualInstructions() {
        Console.println("");
        Console.println("Manual installation instructions:", ConsoleColor.YELLOW);
        Console.println("");
        
        if (PlatformUtils.isWindows()) {
            Console.println("1. Create a file called 'beap.cmd' in your Haxe directory", ConsoleColor.WHITE);
            Console.println("2. Add this content:", ConsoleColor.WHITE);
            Console.println("   @echo off", ConsoleColor.CYAN);
            Console.println("   neko \"" + Sys.getCwd() + "/bin/beap.n\" %*", ConsoleColor.CYAN);
            Console.println("");
            Console.println("3. Make sure the Haxe directory is in your PATH", ConsoleColor.WHITE);
        } else {
            Console.println("1. Create a script file: ~/.local/bin/beap", ConsoleColor.WHITE);
            Console.println("2. Add this content:", ConsoleColor.WHITE);
            Console.println("   #!/bin/bash", ConsoleColor.CYAN);
            Console.println("   neko \"" + Sys.getCwd() + "/bin/beap.n\" \"$$@\"", ConsoleColor.CYAN);
            Console.println("");
            Console.println("3. Make it executable: chmod +x ~/.local/bin/beap", ConsoleColor.WHITE);
            Console.println("4. Add ~/.local/bin to your PATH if not already", ConsoleColor.WHITE);
        }
    }
}